//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknicService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaultDetail
    {
        public System.Guid FaultDetailID { get; set; }
        public System.Guid ProcessID { get; set; }
        public string Fault { get; set; }
        public string Detail { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
    
        public virtual TeknicService TeknicService { get; set; }
    }
}
