//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknicService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public System.Guid OrderDetailId { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid InvoiceID { get; set; }
        public short Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Price { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Products Products { get; set; }
    }
}
