//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknicService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMovement
    {
        public System.Guid MovementID { get; set; }
        public System.Guid ProductID { get; set; }
        public System.Guid CustomerID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public string MovementType { get; set; }
        public Nullable<System.DateTime> MovementDate { get; set; }
        public short Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }
    }
}
