CREATE TABLE [dbo].[Cities] (
    [CityId]  UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CityName VARCHAR(255),
    StateName VARCHAR(255),
    PostalCode VARCHAR(10)
     CONSTRAINT [PK_Cities] PRIMARY KEY CLUSTERED ([CityId] ASC)
);

-- Şehirleri, eyaletleri ve posta kodlarını ekleyin
INSERT INTO Cities (CityName, StateName, PostalCode) VALUES
('Oslo', 'Oslo', '0010'),
('Bergen', 'Hordaland', '5000'),
('Trondheim', 'Trøndelag', '7000'),
('Stavanger', 'Rogaland', '4000'),
('Drammen', 'Buskerud', '3000'),
('Fredrikstad', 'Østfold', '1600'),
('Sandnes', 'Rogaland', '4300'),
('Kristiansand', 'Agder', '4600'),
('Tromsø', 'Troms og Finnmark', '9000'),
('Sarpsborg', 'Østfold', '1700'),
('Skien', 'Telemark', '3700'),
('Alesund', 'Møre og Romsdal', '6000'),
('Sandefjord', 'Vestfold og Telemark', '3200'),
('Haugesund', 'Rogaland', '5500'),
('Tønsberg', 'Vestfold og Telemark', '3100'),
('Molde', 'Møre og Romsdal', '6400'),
('Halden', 'Viken', '1767'),
('Larvik', 'Vestfold og Telemark', '3255'),
('Askøy', 'Vestland', '5302'),
('Kristiansund', 'Møre og Romsdal', '6500'),
('Harstad', 'Troms og Finnmark', '9400'),
('Narvik', 'Nordland', '8514'),
('Lillehammer', 'Innlandet', '2609'),
('Moss', 'Viken', '1530'),
('Ski', 'Viken', '1400'),
('Drøbak', 'Viken', '1440'),
('Kongsberg', 'Viken', '3616'),
('Nesoddtangen', 'Viken', '1450'),
('Mandal', 'Agder', '4514'),
('Horten', 'Vestfold og Telemark', '3182'),
('Gjovik', 'Innlandet', '2815'),
('Hamar', 'Innlandet', '2300'),
('Arendal', 'Agder', '4848'),
('Molde', 'Møre og Romsdal', '6413'),
('Hønefoss', 'Viken', '3510'),
('Kristiansund', 'Møre og Romsdal', '6529'),
('Haugesund', 'Rogaland', '5546'),
('Porsgrunn', 'Vestfold og Telemark', '3916'),
('Oslo', 'Oslo', '0653'),
('Bergen', 'Hordaland', '5254'),
('Trondheim', 'Trøndelag', '7030'),
('Stavanger', 'Rogaland', '4010'),
('Drammen', 'Buskerud', '3014'),
('Fredrikstad', 'Østfold', '1617'),
('Sandnes', 'Rogaland', '4312');