//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknicService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeknicService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeknicService()
        {
            this.FaultDetail = new HashSet<FaultDetail>();
            this.Tracking = new HashSet<Tracking>();
        }
    
        public System.Guid ProcessID { get; set; }
        public System.Guid ProductID { get; set; }
        public System.Guid CustomerID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public System.DateTime TheArrivalDate { get; set; }
        public System.DateTime TheReleaseDate { get; set; }
        public bool Status { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaultDetail> FaultDetail { get; set; }
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tracking> Tracking { get; set; }
    }
}
