//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknicService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public System.Guid TrackingID { get; set; }
        public System.Guid ProcessID { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
    
        public virtual TeknicService TeknicService { get; set; }
    }
}
